import {
  ArrowRight,
  BadgeCheck,
  Bell,
  Building2,
  Calculator,
  ChartNoAxesCombined,
  CheckCircle2,
  CircleDot,
  ClipboardCheck,
  Clock3,
  FileCheck2,
  FileSignature,
  FileText,
  Globe,
  Handshake,
  Headset,
  House,
  Images,
  Landmark,
  LayoutDashboard,
  ListFilter,
  LockKeyhole,
  Mail,
  MapPin,
  MonitorSmartphone,
  NotebookPen,
  PhoneCall,
  Plus,
  Radio,
  Send,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  Sun,
  Users,
  Wallet,
  WalletCards,
  Zap
} from "lucide-react";
import { IconName } from "@/lib/types";

export const iconMap = {
  "arrow-right": ArrowRight,
  "badge-check": BadgeCheck,
  bell: Bell,
  "building-2": Building2,
  calculator: Calculator,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "check-circle-2": CheckCircle2,
  "circle-dot": CircleDot,
  "clipboard-check": ClipboardCheck,
  "clock-3": Clock3,
  "file-check-2": FileCheck2,
  "file-signature": FileSignature,
  "file-text": FileText,
  globe: Globe,
  handshake: Handshake,
  headset: Headset,
  house: House,
  images: Images,
  landmark: Landmark,
  "layout-dashboard": LayoutDashboard,
  "list-filter": ListFilter,
  "lock-keyhole": LockKeyhole,
  mail: Mail,
  "map-pin": MapPin,
  "monitor-smartphone": MonitorSmartphone,
  "notebook-pen": NotebookPen,
  "phone-call": PhoneCall,
  plus: Plus,
  radio: Radio,
  send: Send,
  "settings-2": Settings2,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  sun: Sun,
  users: Users,
  wallet: Wallet,
  "wallet-cards": WalletCards,
  zap: Zap
} as const;

export const iconOptions: { label: string; value: IconName }[] = [
  { label: "Arrow Right", value: "arrow-right" },
  { label: "Badge Check", value: "badge-check" },
  { label: "Bell", value: "bell" },
  { label: "Building", value: "building-2" },
  { label: "Calculator", value: "calculator" },
  { label: "Chart", value: "chart-no-axes-combined" },
  { label: "Check Circle", value: "check-circle-2" },
  { label: "Circle Dot", value: "circle-dot" },
  { label: "Clipboard Check", value: "clipboard-check" },
  { label: "Clock", value: "clock-3" },
  { label: "File Check", value: "file-check-2" },
  { label: "File Signature", value: "file-signature" },
  { label: "File Text", value: "file-text" },
  { label: "Globe", value: "globe" },
  { label: "Handshake", value: "handshake" },
  { label: "Headset", value: "headset" },
  { label: "House", value: "house" },
  { label: "Images", value: "images" },
  { label: "Landmark", value: "landmark" },
  { label: "Dashboard", value: "layout-dashboard" },
  { label: "List Filter", value: "list-filter" },
  { label: "Lock", value: "lock-keyhole" },
  { label: "Mail", value: "mail" },
  { label: "Map Pin", value: "map-pin" },
  { label: "Monitor", value: "monitor-smartphone" },
  { label: "Notebook", value: "notebook-pen" },
  { label: "Phone", value: "phone-call" },
  { label: "Plus", value: "plus" },
  { label: "Radio", value: "radio" },
  { label: "Send", value: "send" },
  { label: "Settings", value: "settings-2" },
  { label: "Shield Alert", value: "shield-alert" },
  { label: "Shield Check", value: "shield-check" },
  { label: "Sun", value: "sun" },
  { label: "Users", value: "users" },
  { label: "Wallet", value: "wallet" },
  { label: "Wallet Cards", value: "wallet-cards" },
  { label: "Zap", value: "zap" }
];
